# Rarity for House - Raridade para Casa
# rarity: ["common", "rare", "super_rare", "epic", "legend", "super_legend"]

1: {mode: "treasure_hunt", username: "youruser", password: "yourpassword", house: false, rarity: []}
